// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { StakeToken$Type } from "./StakeToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StakeToken"]: StakeToken$Type;
    ["contracts/stakeReward/StakeToken.sol:StakeToken"]: StakeToken$Type;
  }

  interface ContractTypesMap {
    ["StakeToken"]: GetContractReturnType<StakeToken$Type["abi"]>;
    ["contracts/stakeReward/StakeToken.sol:StakeToken"]: GetContractReturnType<StakeToken$Type["abi"]>;
  }
}
