// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Message$Type } from "./Message";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Message"]: Message$Type;
    ["contracts/Message.sol:Message"]: Message$Type;
  }

  interface ContractTypesMap {
    ["Message"]: GetContractReturnType<Message$Type["abi"]>;
    ["contracts/Message.sol:Message"]: GetContractReturnType<Message$Type["abi"]>;
  }
}
