// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { KryptoPunksToken$Type } from "./KryptoPunksToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["KryptoPunksToken"]: KryptoPunksToken$Type;
    ["contracts/nft-stake/KryptoPunksToken.sol:KryptoPunksToken"]: KryptoPunksToken$Type;
  }

  interface ContractTypesMap {
    ["KryptoPunksToken"]: GetContractReturnType<KryptoPunksToken$Type["abi"]>;
    ["contracts/nft-stake/KryptoPunksToken.sol:KryptoPunksToken"]: GetContractReturnType<KryptoPunksToken$Type["abi"]>;
  }
}
