// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TodoContract$Type } from "./TodoContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TodoContract"]: TodoContract$Type;
    ["contracts/TodoContract.sol:TodoContract"]: TodoContract$Type;
  }

  interface ContractTypesMap {
    ["TodoContract"]: GetContractReturnType<TodoContract$Type["abi"]>;
    ["contracts/TodoContract.sol:TodoContract"]: GetContractReturnType<TodoContract$Type["abi"]>;
  }
}
