// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IKryptoPunksToken$Type } from "./IKryptoPunksToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IKryptoPunksToken"]: IKryptoPunksToken$Type;
    ["contracts/nft-stake/interfaces/IKryptoPunksToken.sol:IKryptoPunksToken"]: IKryptoPunksToken$Type;
  }

  interface ContractTypesMap {
    ["IKryptoPunksToken"]: GetContractReturnType<IKryptoPunksToken$Type["abi"]>;
    ["contracts/nft-stake/interfaces/IKryptoPunksToken.sol:IKryptoPunksToken"]: GetContractReturnType<IKryptoPunksToken$Type["abi"]>;
  }
}
