// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RewardToken$Type } from "./RewardToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RewardToken"]: RewardToken$Type;
    ["contracts/stakeReward/RewardToken.sol:RewardToken"]: RewardToken$Type;
  }

  interface ContractTypesMap {
    ["RewardToken"]: GetContractReturnType<RewardToken$Type["abi"]>;
    ["contracts/stakeReward/RewardToken.sol:RewardToken"]: GetContractReturnType<RewardToken$Type["abi"]>;
  }
}
