// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Staking$Type } from "./Staking";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Staking"]: Staking$Type;
    ["contracts/stakeReward/Staking.sol:Staking"]: Staking$Type;
  }

  interface ContractTypesMap {
    ["Staking"]: GetContractReturnType<Staking$Type["abi"]>;
    ["contracts/stakeReward/Staking.sol:Staking"]: GetContractReturnType<Staking$Type["abi"]>;
  }
}
