// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { KryptoPunks$Type } from "./KryptoPunks";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["KryptoPunks"]: KryptoPunks$Type;
    ["contracts/nft-stake/KryptoPunks.sol:KryptoPunks"]: KryptoPunks$Type;
  }

  interface ContractTypesMap {
    ["KryptoPunks"]: GetContractReturnType<KryptoPunks$Type["abi"]>;
    ["contracts/nft-stake/KryptoPunks.sol:KryptoPunks"]: GetContractReturnType<KryptoPunks$Type["abi"]>;
  }
}
