// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IKryptoPunks$Type } from "./IKryptoPunks";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IKryptoPunks"]: IKryptoPunks$Type;
    ["contracts/nft-stake/interfaces/IKryptoPunks.sol:IKryptoPunks"]: IKryptoPunks$Type;
  }

  interface ContractTypesMap {
    ["IKryptoPunks"]: GetContractReturnType<IKryptoPunks$Type["abi"]>;
    ["contracts/nft-stake/interfaces/IKryptoPunks.sol:IKryptoPunks"]: GetContractReturnType<IKryptoPunks$Type["abi"]>;
  }
}
