// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AddCount$Type } from "./AddCount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AddCount"]: AddCount$Type;
    ["contracts/AddCount.sol:AddCount"]: AddCount$Type;
  }

  interface ContractTypesMap {
    ["AddCount"]: GetContractReturnType<AddCount$Type["abi"]>;
    ["contracts/AddCount.sol:AddCount"]: GetContractReturnType<AddCount$Type["abi"]>;
  }
}
