// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NFT$Type } from "./NFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NFT"]: NFT$Type;
    ["contracts/NFT.sol:NFT"]: NFT$Type;
  }

  interface ContractTypesMap {
    ["NFT"]: GetContractReturnType<NFT$Type["abi"]>;
    ["contracts/NFT.sol:NFT"]: GetContractReturnType<NFT$Type["abi"]>;
  }
}
